# Generated by Django 3.0.8 on 2020-07-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qusetion_text',
            new_name='question_text',
        ),
    ]
